(define (caar pair) (car (car pair)))
(define (cadr pair) (car (cdr pair)))
(define (cdar pair) (cdr (car pair)))
(define (cddr pair) (cdr (cdr pair)))
(define (caaar pair) (car (car (car pair))))
(define (caadr pair) (car (car (cdr pair))))
(define (cadar pair) (car (cdr (car pair))))
(define (caddr pair) (car (cdr (cdr pair))))
(define (cdaar pair) (cdr (car (car pair))))
(define (cdadr pair) (cdr (car (cdr pair))))
(define (cddar pair) (cdr (cdr (car pair))))
(define (cdddr pair) (cdr (cdr (cdr pair))))
(define (caaaar pair) (car (car (car (car pair)))))
(define (caaadr pair) (car (car (car (cdr pair)))))
(define (caadar pair) (car (car (cdr (car pair)))))
(define (caaddr pair) (car (car (cdr (cdr pair)))))
(define (cadaar pair) (car (cdr (car (car pair)))))
(define (cadadr pair) (car (cdr (car (cdr pair)))))
(define (caddar pair) (car (cdr (cdr (car pair)))))
(define (cadddr pair) (car (cdr (cdr (cdr pair)))))
(define (cdaaar pair) (cdr (car (car (car pair)))))
(define (cdaadr pair) (cdr (car (car (cdr pair)))))
(define (cdadar pair) (cdr (car (cdr (car pair)))))
(define (cdaddr pair) (cdr (car (cdr (cdr pair)))))
(define (cddaar pair) (cdr (cdr (car (car pair)))))
(define (cddadr pair) (cdr (cdr (car (cdr pair)))))
(define (cdddar pair) (cdr (cdr (cdr (car pair)))))
(define (cddddr pair) (cdr (cdr (cdr (cdr pair)))))
(define (not x) (i f x #f #t ) )
(define (null ? obj) (i f (eqv? obj ’ ()) #t #f ))
(define (id obj) obj)
(define (f l i p func) (lambda (arg1 arg2) (func arg2 arg1)))
(define (curry func arg1) (lambda (arg) (func arg1 arg)))
(define (compose f g) (lambda (arg) (f (g arg)))
( define ( foldl func accum lst )
  ( if ( null ? lst )
    accum
    ( foldl func ( func accum ( car lst ) ) ( cdr lst ) ) ) )
( define ( foldr func accum lst )
  ( i f ( null ? lst )
    accum
    ( func ( car lst) (foldr func accum ( cdr lst ) ) ) ) )
( define ( foldr func accum lst )
  ( if ( null ? lst )
    accum
    ( func ( car lst) (foldr func accum ( cdr lst ) ) ) ) )
( define fold foldl )
( define reduce fold )
( define zero? (curry = 0))
( define pos i t i v e? (curry < 0) )
( define negative? (curry > 0) )
( define (odd? num) (= (mod num 2) 1) )
( define (even? num) (= (mod num 2) 0) )
( define (max x . num−l i s t ) (fold ( lambda ( y z) (i f (> y z ) y z ) ) x num− l i s t ) )
( define (min x . num−l i s t ) (fold ( lambda ( y z) (i f (< y z ) y z ) ) x num− l i s t ) )
( define ( l i s t . objs ) objs )
( define ( length lst) (fold ( lambda ( x y) (+ x 1) ) 0 lst ) )
( define ( append lst . lst s) (foldr ( f l i p ( curry foldr cons ) ) lst lst s ) )
( define ( reverse lst) (fold ( f l i p cons) ’() lst ) )
( define (mem−helper pred op) (lambda ( acc next) (i f (and (not acc) (pred
( op next) ) ) next acc ) ) )
( define (memq obj lst) (fold (mem−helper ( curry eq? obj ) id) #f
lst ) )
( define (memv obj lst) (fold (mem−helper ( curry eqv? obj ) id) #f
lst ) )
( define (member obj lst) (fold (mem−helper ( curry equal ? obj ) id) #f
lst ) )
( define ( assq obj a l i s t) (fold (mem−helper ( curry eq? obj ) car) #f
a l i s t ) )
( define ( assv obj a l i s t) (fold (mem−helper ( curry eqv? obj ) car) #f
a l i s t ) )
( define ( assoc obj a l i s t) (fold (mem−helper ( curry equal ? obj ) car) #
f a l i s t ) )
( define (map func lst) (foldr ( lambda ( x y) (cons ( func x ) y) ) ’()
lst ) )
( define ( f i l t e r pred lst) (foldr ( lambda ( x y) (i f (pred x) (cons x y )
y) ) ’() lst ) )
( define (sum . lst) (fold + 0 lst ) )
( define (product . lst) (fold ⇤ 1 lst ) )
( define (and . lst) (fold && #t lst ) )
( define ( or . lst) (fold | | #f lst ) )
( define (any? pred . lst) (apply or (map pred lst ) ) )
( define ( every ? pred . lst) (apply and (map pred lst ) ) )
